# Generated by Django 3.2.12 on 2022-05-14 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gammer_tag', models.CharField(max_length=255)),
                ('display_image', models.ImageField(blank=True, default='call-of-duty.jpeg', null=True, upload_to='game_logos')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='UserMatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.tournament')),
                ('usermatchparticipant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.usergame')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrophyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='games.badgescategory')),
                ('usertrophycase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.usermatchparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.ManyToManyField(to='games.Platform')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usergame',
            name='userplatform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.userplatform'),
        ),
    ]
