# Generated by Django 3.2.10 on 2022-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IGL_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='index_points',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
